### ISSUE TITLE
Unexpected value '[object Object]' imported by the module 'TemplateModule'

### ISSUE THREAD

**Issue by tylkomat** [patrikx3/ng2-compile-html#1]
I followed the example in the readme, but somehow can not get it to work.

```html
<div [p3x-compile-html]="task.question" [p3x-compile-html-ref]="task.parameters"></div>
```
```ts
import { Component, Injectable } from '@angular/core';

import { TaskConfig } from './task-config';

@Component({
  selector: 'text-task-puzzle',
  templateUrl: 'text-task-puzzle.html'
})
@Injectable()
export class TextTaskPuzzleComponent {

  public task: TaskConfig = {
    parameters: {
      ernte: 4500,
      ausfall: 300,
      preis: 1.20
    },
    question: '{{ ref.ernte }}'
  };

  constructor() {}
}
```

I was also trying with:
```ts
public ref: TextTaskPuzzleComponent;
constructor() {
  this.ref = ref;
}
```

**Comment by patrikx3** [comment]
repreduce

**Comment by patrikx3** [comment]
all latest version, typscript latest, also in patrikx3/corifeus-web-pages is already using imports, check the code as well

**Comment by tylkomat** [comment]
You are too fast. Accidentally hit Enter and the issue was published before I finished, or even started ^^. See update at the top.

**Comment by patrikx3** [comment]
you did  not added in the imports , check the imports in the readme

**Comment by patrikx3** [comment]
<div #container></div>
 <div [p3x-compile-html]="data2" [p3x-compile-html-ref]="ref" [p3x-compile-html-imports]="importsLikeMaterialEtc"></div>

check it how corifeus-web-pages does it, ciao

**Comment by patrikx3** [comment]
'''html
 <div #container></div>
 <div [p3x-compile-html]="data2" [p3x-compile-html-ref]="ref" [p3x-compile-html-imports]="importsLikeMaterialEtc"></div>
'''

**Comment by patrikx3** [comment]
'''html
 <div #container></div>
 <div [p3x-compile-html]="data2" [p3x-compile-html-ref]="ref" [p3x-compile-html-imports]="importsLikeMaterialEtc"></div>
'''

**Comment by tylkomat** [comment]
Which Imports to you mean? I added them in my `app.modules.ts` Otherwise it would not have parsed the attribute and generated the `TemplateModule`.

**Comment by patrikx3** [comment]
it creates a dynamic import, thats why needed it is in p3x-compile-html-imports, you are not looking in my repo, also missing the readme. also your code is missing the import. it is an array of modules.

**Comment by patrikx3** [comment]
https://github.com/patrikx3/corifeus-web-pages/blob/master/src/angular2/layout/cory-page.ts

also in the html for the same file.

**Comment by tylkomat** [comment]
Here are the complete files I'm using. There is imports and everything. Still the same problem.
```ts
import { Component, PipeTransform, Injectable } from '@angular/core';
import { DecimalPipe } from '@angular/common';

import { TaskConfig } from './task-config';

@Component({
  selector: 'text-task-puzzle',
  templateUrl: 'text-task-puzzle.html'
})
@Injectable()
export class TextTaskPuzzleComponent {

  public task: TaskConfig = {
    parameters: {
      ernte: 4500,
      ausfall: 300,
      preis: 1.20
    },
    question: 'Der Bauer erntet jedes Jahr {{ ref.ernte }} Kilogramm (kg) Äpfel auf seiner Streuobstwiese. Von \
      den {{ ref.ernte }} Kilogramm kann er {{ ref.ausfall }} Kilogramm nicht verkaufen, weil das Obst wurmstichig ist. \
      Für 1 Kilogramm ungespritzte Bio-Äpfel bekommt der Bauer {{ ref.preis | number: "1,2-2" }} Euro. \
      Frage: Wie viel Geld verdient der Bauer mit den Äpfeln von seiner Streuobstwiese?',
    steps: [
      {
        text: '{{ ernte }} kg - {{ ausfall }} kg =',
        formular: 'ernte - ausfall',
        result: '{{ step1Result }} kg.'
      },
      {
        text: '{{ step1Result }} kg x {{ preis | number: "1,2-2" }} Euro / kg =',
        formular: 'step1Result x preis',
        result: '{{ step2Result }} Euro.'
      }
    ],
    result: 'Antwort: Der Bauer verdient {{ step3Result }} Euro.'
  };

  public imports: Array<any> = [
    new DecimalPipe('')
  ];

  constructor() {

  }
}
```
```html
<div [p3x-compile-html]="task.question" [p3x-compile-html-ref]="task.parameters" [p3x-compile-html-imports]="imports"></div>
```

**Comment by patrikx3** [comment]
whats the error?

**Comment by tylkomat** [comment]
Error in ./TextTaskPuzzleComponent class TextTaskPuzzleComponent - inline template:0:81 caused by: Unexpected value '[object Object]' imported by the module 'TemplateModule'

**Comment by patrikx3** [comment]
where can i  clone the code to debug out?

**Comment by patrikx3** [comment]
is it really a p3x error? the error is in your code, not in p3x...

**Comment by patrikx3** [comment]
also stacktrace is better

**Comment by tylkomat** [comment]
Thanks I found it. Was adding the DecimalPipe in a wrong way.
